<?php

namespace App\Http\Controllers\Admin\Tour;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Http\JsonResponse;

use App\Http\Controllers\Controller;
use App\Interfaces\LocationRepositoryInterface;
use App\Interfaces\Tour\BespokeRepositoryInterface;
use App\Http\Requests\Tour\Bespoke\StoreRequest;
use App\Models\Tour;
use App\Http\Requests\Tour\Bespoke\UpdateRequest;

class BespokeController extends Controller
{
    public function __construct(
        private readonly BespokeRepositoryInterface $bespokeRepository,
        private readonly LocationRepositoryInterface $locationRepository,
    ) {}

    public function index(Request $request)
    {
        $filters = $request->only(['search', 'location_id', 'status', 'category_id']);
        $tours = $this->bespokeRepository->index($filters);

        return view('admin.tours.bespoke.index', compact('tours'));
    }

    public function create()
    {
        $locations = $this->locationRepository->getAll();

        return view('admin.tours.bespoke.create', compact('locations'));
    }

    public function store(StoreRequest $request)
    {
        $validated = $request->validated();

        $tour = null;
        DB::transaction(function () use ($validated, $request, &$tour) {
            $tourData = [
                'title' => $validated['title'],
                'slug' => null, // Will be generated by the repository
                'description' => $validated['description'],
                'tour_category_id' => 4, // Multiple Day Tours category for bespoke
                'location_id' => $validated['location_id'],
                'status' => 'draft',
                'tour_type' => 'bespoke',
                'code' => $validated['code'],
            ];

            $tour = $this->bespokeRepository->store($tourData);
        });

        return redirect()
            ->route('console.tours.bespoke.show', $tour)
            ->with('success', 'Bespoke tour created successfully.');
    }

    public function show(Tour $tour)
    {
        $tour = $this->bespokeRepository->findBySlug($tour->slug);

        if (!$tour) {
            abort(404);
        }

        if (($tour->tour_type ?? 'standard') !== 'bespoke') {
            return redirect()
                ->route('console.tours.standard.show', $tour)
                ->with('warning', 'This tour is not a bespoke tour.');
        }

        return view('admin.tours.bespoke.show', compact('tour'));
    }

    public function edit(Tour $tour)
    {
        if (($tour->tour_type ?? 'standard') !== 'bespoke') {
            return redirect()
                ->route('console.tours.edit', $tour)
                ->with('warning', 'This tour is not a bespoke tour.');
        }

        $locations = $this->locationRepository->getAll();

        return view('admin.tours.bespoke.edit', compact('tour', 'locations'));
    }

    public function update(UpdateRequest $request, Tour $tour)
    {
        if (($tour->tour_type ?? 'standard') !== 'bespoke') {
            return redirect()
                ->route('console.tours.edit', $tour)
                ->with('warning', 'This tour is not a bespoke tour.');
        }

        $validated = $request->validated();

        DB::transaction(function () use ($validated, $tour) {
            $this->bespokeRepository->update($tour, $validated);
        });

        return redirect()
            ->route('console.tours.bespoke.show', $tour)
            ->with('success', 'Bespoke tour updated successfully.');
    }

    /**
     * Generate a share link for the bespoke tour
     */
    public function generateShareLink(Request $request, Tour $tour): JsonResponse
    {
        if (($tour->tour_type ?? 'standard') !== 'bespoke') {
            return response()->json([
                'success' => false,
                'message' => 'Share links are only available for bespoke tours.'
            ], 403);
        }

        try {
            $tour->markAsReadyToShare();
            
            return response()->json([
                'success' => true,
                'message' => 'Share link generated successfully.',
                'share_url' => $tour->share_url,
                'expires_at' => $tour->expires_at->format('Y-m-d H:i:s')
            ]);
        } catch (\Exception $e) {
            return response()->json([
                'success' => false,
                'message' => 'Failed to generate share link: ' . $e->getMessage()
            ], 500);
        }
    }
}
