<?php

namespace App\Http\Controllers\Admin\Tour;

use Illuminate\Support\Facades\DB;

use App\Http\Controllers\Controller;
use App\Http\Requests\Tour\Bespoke\StoreRequest;
use App\Http\Requests\Tour\Bespoke\UpdateRequest;
use App\Interfaces\LocationRepositoryInterface;
use App\Interfaces\Tour\BespokeRepositoryInterface;
use App\Models\Tour;

class BespokeController extends Controller
{
    public function __construct(
        private readonly LocationRepositoryInterface $locationRepository,
        private readonly BespokeRepositoryInterface $bespokeRepository
    ) {}

    public function index()
    {
        throw new \Exception('Not implemented');
    }

    public function create()
    {
        $locations = $this->locationRepository->getAll();

        return view('admin.tours.bespoke.create', compact('locations'));
    }

    public function store(StoreRequest $request)
    {
        $validated = $request->validated();

        $tour = null;
        DB::transaction(function () use ($validated, $request, &$tour) {
            $tourData = [
                'title' => $validated['title'],
                'slug' => null, // Will be generated by the repository
                'description' => $validated['description'],
                'tour_category_id' => 4, // Multiple Day Tours category for bespoke
                'location_id' => $validated['location_id'],
                'status' => 'draft',
                'tour_type' => 'bespoke',
                'code' => $validated['code'],
            ];

            $tour = $this->bespokeRepository->store($tourData);
        });

        return redirect()
            ->route('console.tours.show', $tour->fresh())
            ->with('success', 'Bespoke tour created successfully.');
    }

    public function show(Tour $tour)
    {
        $tour = $this->bespokeRepository->findBySlug($tour->slug);

        if (!$tour) {
            abort(404);
        }

        if (($tour->tour_type ?? 'standard') !== 'bespoke') {
            return redirect()
                ->route('console.tours.show', $tour)
                ->with('warning', 'This tour is not a bespoke tour.');
        }

        return view('admin.tours.bespoke.show', compact('tour'));
    }

    public function edit(Tour $tour)
    {
        if (($tour->tour_type ?? 'standard') !== 'bespoke') {
            return redirect()
                ->route('console.tours.edit', $tour)
                ->with('warning', 'This tour is not a bespoke tour.');
        }

        $locations = $this->locationRepository->getAll();

        return view('admin.tours.bespoke.edit', compact('tour', 'locations'));
    }

    public function update(UpdateRequest $request, Tour $tour)
    {
        if (($tour->tour_type ?? 'standard') !== 'bespoke') {
            return redirect()
                ->route('console.tours.edit', $tour)
                ->with('warning', 'This tour is not a bespoke tour.');
        }

        $validated = $request->validated();

        DB::transaction(function () use ($validated, $tour) {
            $this->bespokeRepository->update($tour, $validated);
        });

        return redirect()
            ->route('console.tours.show', $tour->fresh())
            ->with('success', 'Bespoke tour updated successfully.');
    }

    public function destroy(Tour $tour)
    {
        throw new \Exception('Not implemented');
    }
}
